name: Pydra

on: [push, pull_request]

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04-16core]
        python-version: [3.7, 3.8, 3.9, '3.10']
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Disable etelemetry
      run: echo "NO_ET=TRUE" >> $GITHUB_ENV
    - name: Active conda env pydra-tutorial
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: pydra-tutorial
        environment-file: environment.yml
        python-version: ${{ matrix.python-version }}
    - run: conda info
    - run: conda list
    - run: conda config --show
    - name: Set git credentials
      run: |
        git config --global user.name "fake user"
        git config --global user.email "fake@email"
    - name: Convert all md files to ipynb
      run: jupytext notebooks/*.md --to ipynb
    - name: Test notebooks with pytest
      run: pytest --nbval-lax --nbval-cell-timeout 7200 -v -s notebooks/
